# Generated by Django 4.0.4 on 2022-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Date_of_Publication', models.CharField(max_length=50)),
                ('Number_of_Pages', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGIONID', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('principal', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('books', models.CharField(max_length=50)),
            ],
        ),
    ]
